[package]
name = "daily"
version = "0.1.0"
authors = ["Jeriel Baptista Verissimo <jeriel@ciandt.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.8.0"
termion = "1.5.5"
